Supporting Sigma v4.0.1 signing functions
ergoplatform/ergo-appkit pull request #117
Opened 2021-12-08 14:09 UTC by dav009

https://github.com/ergoplatform/ergo-appkit/issues/65

👋  ErgoTeam,  I took on this issue to get more familiar with the code base.  (tagged as `Good first issue`)
If the code in this PR makes sense I am happy to continue adding the needed unit-tests.

2021-12-12 09:58 UTC, aslesarenko commented
@dav009 Yes, SigmaBoolean is a generalized public key so the code looks good, modulo comments. 
You can also add an overload of the methods which takes P2PKAddress.
Note, P2PKAddress can be either constructed directly or obtained for org.ergoplatform.appkit.Address.

Please go ahead with this PR, everything looks good.

2021-12-12 09:58 UTC, aslesarenko requested changes

2021-12-12 09:58 UTC, aslesarenko commented on lib-api/src/main/java/org/ergoplatform/appkit/ErgoProver.java
> +    boolean verifySignature(SigmaBoolean tx, byte[] message, byte[] signedMessage);
```suggestion
    boolean verifySignature(SigmaBoolean sigmaTree, byte[] message, byte[] signedMessage);
```

2021-12-12 09:58 UTC, aslesarenko commented on lib-impl/src/main/java/org/ergoplatform/appkit/impl/ErgoProverImpl.scala
> +
```suggestion
```
Please remove unnecessary blank lines.

2021-12-14 02:59 UTC, dav009 commented
@aslesarenko added some unit tests . 
CI is still failing when publishing the snapshot artifacts 🤔 .

2021-12-15 13:45 UTC, aslesarenko commented on lib-api/src/main/java/org/ergoplatform/appkit/ErgoProver.java
> +    byte[] signMessage(SigmaBoolean sigmaTree, byte[] message, HintsBag hintsBag);
Every public method need full documentation including: 1) description 2) all parameter 3) return value. 
In general, the description shouldn't just repeat what is obvious from the signature, instead it should complement it with special considerations derived from the essence of the method (something you would want to read, it is were not your method)

2021-12-15 14:27 UTC, aslesarenko requested changes

2021-12-16 17:05 UTC, aslesarenko approved these changes

2021-12-16 17:05 UTC, aslesarenko commented on lib-api/src/main/java/org/ergoplatform/appkit/ErgoProver.java
> +     /**
```suggestion
    /**
```

2021-12-16 17:05 UTC, aslesarenko commented on lib-api/src/main/java/org/ergoplatform/appkit/ErgoProver.java
> +     /**
```suggestion
    /**
```

2021-12-16 17:06 UTC, aslesarenko commented
Now looks good, waiting for tests

2021-12-17 01:40 UTC, dav009 commented
@aslesarenko  added a round trip sign/verification.

2021-12-17 07:47 UTC, merged