BoxOperations: Consider amount for change box
ergoplatform/ergo-appkit pull request #141
Opened 2022-02-22 08:36 UTC by MrStahlfelge

When we have tokens in selected inboxes that shouldn't be sent, a change box is needed to return the tokens to the sending address. That means that a small amount of ERG is needed on top of the actual amount to send which must be considered when selecting boxes.

This change adds the ability to BoxOperations to account for a change box amount and an accompanying test case. However, the test case files although BoxOperations is now correctly selecting the two boxes of the test case. This is due to `DefaultBoxSelector` ignoring the second, needed box which needs to be fixed in ergo-wallet.

2022-02-22 16:52 UTC, aslesarenko requested changes

2022-02-22 16:52 UTC, aslesarenko commented on common/src/main/java/org/ergoplatform/appkit/SelectTokensHelper.java
> +    public void useTokens(Iterable<ErgoToken> foundTokens) {
Please update the doc. It is not clear how tokens are marked. What is means "tokens to find"? Find where?

2022-02-22 16:52 UTC, aslesarenko commented on common/src/main/java/org/ergoplatform/appkit/SelectTokensHelper.java
> +    public boolean isChangeBoxNeeded() {
Please add JavaDoc.

2022-02-22 16:52 UTC, aslesarenko commented on common/src/main/java/org/ergoplatform/appkit/SelectTokensHelper.java
>      public boolean areTokensCovered() {
Please add JavaDoc

2022-02-22 16:52 UTC, aslesarenko commented on common/src/main/java/org/ergoplatform/appkit/SelectTokensHelper.java
>  public class SelectTokensHelper {
Please clarify the description. What "tokens already found" means?

2022-02-22 16:52 UTC, aslesarenko commented on lib-api/src/main/java/org/ergoplatform/appkit/BoxOperations.java
> +            // change box needed but not considered yet?
What it means "considered"? Maybe different verb will serve better.

2022-02-22 16:52 UTC, aslesarenko commented on lib-api/src/main/java/org/ergoplatform/appkit/BoxOperations.java
> +     * @param changeBoxConsidered true if change box is already considered by amountToSpend
the word `considered` is not clear.

2022-02-23 08:23 UTC, MrStahlfelge commented
Addressed the feedback, please check

2022-02-23 13:39 UTC, aslesarenko approved these changes

2022-02-23 17:30 UTC, merged