Make verifySignature static on ErgoProver
ergoplatform/ergo-appkit pull request #148
Opened 2022-03-09 13:39 UTC by MrStahlfelge

verifying a signature is independant from actual prover and doesn't need any secrets, so this changes the code towards being usable without constructing a prover holding secrets.

2022-03-09 16:05 UTC, aslesarenko requested changes

2022-03-09 16:05 UTC, aslesarenko commented on lib-api/src/main/java/org/ergoplatform/appkit/ErgoProver.java
> +    static boolean verifySignature(SigmaBoolean sigmaTree, byte[] message, byte[] signedMessage) {
signedMessage name is misleading, better call it `signature` as in the original method of interpreter.

2022-03-11 14:36 UTC, MrStahlfelge commented on lib-api/src/main/java/org/ergoplatform/appkit/ErgoProver.java
> +    }
Done, as discussed on Discord AppkitProvingInterpreter needs secrets that are not used here.

2022-03-11 16:54 UTC, aslesarenko approved these changes
LGTM, please also apply edit suggestions

2022-03-11 16:54 UTC, aslesarenko commented on common/src/main/java/org/ergoplatform/appkit/Signature.java
> +     * @param sigmaTree     public key (represented as a tree)
```suggestion
     * @param sigmaTree     public key (represented as a sigma proposition tree)
```

2022-03-11 16:54 UTC, aslesarenko commented on common/src/main/java/org/ergoplatform/appkit/Signature.java
> +     * using an address' public key.
```suggestion
     * Verifies a signature on given (arbitrary) message
     * using an address' public key.
```

2022-03-12 13:10 UTC, merged